// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// n64_pi //
// ------ //

#define n64_pi_wrap_target 9
#define n64_pi_wrap 27

static const uint16_t n64_pi_program_instructions[] = {
    0xa0e3, //  0: mov    osr, null                  
    0x6080, //  1: out    pindirs, 32                
    0x2091, //  2: wait   1 gpio, 17                 
    0x2090, //  3: wait   1 gpio, 16                 
    0x2011, //  4: wait   0 gpio, 17                 
    0x4010, //  5: in     pins, 16                   
    0x2010, //  6: wait   0 gpio, 16                 
    0x4010, //  7: in     pins, 16                   
    0x8020, //  8: push   block                      
            //     .wrap_target
    0x00c0, //  9: jmp    pin, 0                     
    0xa0e0, // 10: mov    osr, pins                  
    0x6072, // 11: out    null, 18                   
    0x6041, // 12: out    y, 1                       
    0x0077, // 13: jmp    !y, 23                     
    0x6021, // 14: out    x, 1                       
    0x0049, // 15: jmp    x--, 9                     
    0x8020, // 16: push   block                      
    0x80a0, // 17: pull   block                      
    0x6010, // 18: out    pins, 16                   
    0xa0eb, // 19: mov    osr, !null                 
    0x6080, // 20: out    pindirs, 32                
    0x2093, // 21: wait   1 gpio, 19                 
    0x0009, // 22: jmp    9                          
    0x4010, // 23: in     pins, 16                   
    0xa02b, // 24: mov    x, !null                   
    0x4030, // 25: in     x, 16                      
    0x2092, // 26: wait   1 gpio, 18                 
    0x8020, // 27: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program n64_pi_program = {
    .instructions = n64_pi_program_instructions,
    .length = 28,
    .origin = -1,
};

static inline pio_sm_config n64_pi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + n64_pi_wrap_target, offset + n64_pi_wrap);
    return c;
}

void n64_pi_program_init(PIO pio, uint sm, uint offset) {
    // gpio0 -> 22 input
    for (int i = 0; i <= 22; i++) {
        pio_gpio_init(pio, i);
    }
    // LA1, LA2
    pio_gpio_init(pio, 26);
    pio_gpio_init(pio, 27);
    // AD0 -> AD15 input
    // gpio 0 -> 22 are input for now
    pio_sm_set_consecutive_pindirs(pio, sm, 0, 23, false);
    // Set 26, 27 as outputs
    pio_sm_set_consecutive_pindirs(pio, sm, 26, 2, true);
    pio_sm_config c = n64_pi_program_get_default_config(offset);
    // 26, 27 = set pins
    sm_config_set_set_pins(&c, 26, 2);
    // AD0 -> AD16 as in pins
    sm_config_set_in_pins(&c, 0);
    // AD0 -> AD16 as out pins
    sm_config_set_out_pins(&c, 0, 16);
    // JMP pin = ALEH
    sm_config_set_jmp_pin(&c, 17);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

